Debug: true
HTTPBind: :8090
Slat: b10adc3749ba50cbbe76e057f20f8876
Mysql:
  DbDsn: root:123456@tcp(127.0.0.1:3306)/echoframe?charset=utf8mb4
  ShowSql: true
Redis:
  RedisAddr: 127.0.0.1:7379
  Password: 123456
  RedisDb: 1
Logger:
  Path: ./log/echoframe.log
  MaxSize: 10240
  MaxAge: 7
  Compress: true
  LocalTime: true
Jwt:
  Expire: 3600
  SECRET: 90fc4956fb1d4f0f963d8cc2a3bf86e934234223423
LevelDBPath: ./leveldb_data
MongoDB: mongodb://127.0.0.1:27017/?maxPoolSize=20&w=majority
