debug: true
port: :8081
slat: b10adc3749ba50cbbe76e057f20f8876
mysql:
  dsn: root:123456@tcp(127.0.0.1:3306)/echo_frame?charset=utf8mb4
  show: true
redis:
  url: 127.0.0.1:6379
  password: 123456
  db: 1
logger:
  path: /logs/app.log
  ormLog: /logs/orm.log
  max: 10240
  live: 7
  compress: true
  localTime: true
jwt:
  expire: 3600
  secret: 11ac4965fb2d4f0f063d1ccba3bf76e134204223429
leveldb: /leveldb_data
mongodb: mongodb://127.0.0.1:27017/?maxPoolSize=20&w=majority
es: https://127.0.0.1:9200
